### ISSUE TITLE
published helm chart

### ISSUE THREAD

**Issue by rawlingsj** [mittwald/kubernetes-replicator#10]
@martin-helmich we really love this idea!  Not tried using it yet but we're about to try and use this to replicate secrets containing wildcard certs from LetsEncrypt into selected namespaces.  I work on an OSS project called Jenkins X https://jenkins-x.io/ and providing things work well then we'll make it available for all users to include easily into their own Jenkins X installs.  For now we'll probably fork this repo so we can publish the helm chart so that it's easy for us and others to install.  Any changes we make we will contribute back of course.  

Awesome work :)

**Comment by martin-helmich** [comment]
Hey @rawlingsj, thanks for the encouraging feedback. Just give me a ping if you need anything.
