### ISSUE TITLE
Helm chart for 2.6.0 is not published

### ISSUE THREAD

**Issue by uncycler** [mittwald/kubernetes-replicator#109]
**Describe the bug**
It seems that the job that publish the helm chart failed for the 2.6.0 release.

**Comment by elenz97** [comment]
Hey @uncycler,

thanks for letting us know!

Please refer to the latest version, which has just been released with a fix for the release action: https://github.com/mittwald/kubernetes-replicator/releases/tag/v2.6.1

HTH

**Comment by uncycler** [comment]
That was fast! Thanks, I was able to deploy the new version flawlessly.
