### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by derrickburns** [mittwald/kubernetes-replicator#112]
You need to add annotations on secret for which namespaces to allow when you are using the method of using labels on namespaces. Your documentation does NOT reflect this.

**Comment by YannikBramkamp** [comment]
Hello, thank you for your report. Unfortunately I don't quite follow which part in the documentation you are referring to, would you mind elaborating a bit on which section of the documentation contains the issue and perhaps provide a short reproducible example of your scenario? As far as I am aware, using the `replicator.v1.mittwald.de/replicate-to-matching` annotation should not require any additional annotations.
