### ISSUE TITLE
Image version 2.7 isn't released to Quay

### ISSUE THREAD

**Issue by timbuchwaldt** [mittwald/kubernetes-replicator#141]
**Describe the bug**
After updating the Helm chart to 2.7 the image failed to pull from quay.io, a quick check there confirmed the absence of the image.

**Comment by red-avtovo** [comment]
The issue is still there

**Comment by codablock** [comment]
@hensur Issue is still present even after #142 and the v2.7.1 release

**Comment by codablock** [comment]
Sorry, probably tagged the wrong person. Meant to tag @martin-helmich

**Comment by martin-helmich** [comment]
Apologies everyone, I lost track of this one. Let's see if the image is built correctly, now. 🤞
