### ISSUE TITLE
Crashes on Deploy - arm64 - Need architecture detection

### ISSUE THREAD

**Issue by Rojikku** [mittwald/kubernetes-replicator#157]
**Describe the bug**
Upon deployment, either manually or by helmchart, the pod crashes repeatedly.
I have diagnosed this to be because I am deploying to a raspberry Pi.
Normally deployments to things like dockerhub detect the architecture and pull the appropriate version of the container.
It appears your setup has a separate repository for the arm64 version (Though I definitely appreciate that it exists at all).

**To Reproduce**
helm repo add mittwald https://helm.mittwald.de
helm repo update
helm install replicator mittwald/kubernetes-replicator --namespace cert-manager

**To Fix (Poorly, if you want this to work and it hasn't been patched yet)**
helm pull mittwald/kubernetes-replicator
tar xvf kuber*
edit the values.yaml and append -arm64 at the end of the repository line (No spaces)

**Expected behavior**
Automatically detect architecture and use the appropriate docker container (Please?).

**Environment:**
 - Kubernetes version: v1.21.5+k3s2
 - kubernetes-replicator version: v2.6.2
 - RPi4

**Additional context**
This might be a feature request depending on your point of view, but I spent like half an hour trying to figure it out, so I'll go with bug.
If there was a note in the readme.md about it I'd say it was a feature request.

**Comment by martin-helmich** [comment]
No need to manually patch the Helm chart -- you can simply override the `image.repository` value when installing the Helm chart:

```
$ helm install --set image.repository=quay.io/mittwald/kubernetes-replicator-arm64 $release_name mittwald/kubernetes-replicator
```

Although I agree that a multi-architecture image (we're already providing one for mittwald/kube-httpcache) would provide a more seamless experience for non-x86 users. :+1:
