### ISSUE TITLE
Multiarch support

### ISSUE THREAD

**Issue by dewet22** [mittwald/kubernetes-replicator#19]
Supporting `arm`/`arm64` in addition to `amd64` would be great to support multi-arch clusters. It essentially just requires building separate images for each architecture (i.e. `quay.io/mittwald/kubernetes-replicator-amd64:latest`, `quay.io/mittwald/kubernetes-replicator-arm:latest`, etc.) and the publishing an overarching manifest at `quay.io/mittwald/kubernetes-replicator:latest` to point to these. https://docs.docker.com/engine/reference/commandline/manifest/ has all the details and https://billglover.me/2018/10/30/multi-architecture-docker-builds/ has an example build, but I haven't used goreleaser yet so not quite confident making the change myself. It seems pretty easy when you're using the `scratch` base image.

**Comment by Hermsi1337** [comment]
Definitely a good idea. I will get into this soon (=

**Comment by dewet22** [comment]
Wow, thanks for the awesome quick turnaround!
