### ISSUE TITLE
Replicator pod crashing after replicating secret to a large number of namespaces

### ISSUE THREAD

**Issue by cherrera-acx** [mittwald/kubernetes-replicator#214]
**Describe the bug**
We are replicating a secret across 100+ namespaces. Replicator successfully replicates the secret but when its starts to cycle a check on the namespaces to validate that the secret exists the pod crashes, and starts restarting.

**To Reproduce**
Replicate secret 

**Expected behavior**
Secret is successfully replicated without issues

**Environment:**
 - Kubernetes version: [v1.21.14-gke.2100]
 - kubernetes-replicator version: [k8s-replicator-2.7.3]

**Additional context**
We are using replicator to replicate cert-manager tls secrets, following this documentation.
https://cert-manager.io/docs/tutorials/syncing-secrets-across-namespaces/#using-kubernetes-replicator

**Comment by sravanakinapally** [comment]
I have similar issue https://github.com/mittwald/kubernetes-replicator/issues/215

**Comment by cherrera-acx** [comment]
Please keep issue open, as the issue still persists.

**Comment by martin-helmich** [comment]
Apologies; this should not have gotten stale. 🙏  You mentioned the controller crashing after the first reconciliation; do you happen to have any logs available from that moment when the controller crashed?

**Comment by RomanGalochkin** [comment]
I have the same issue.
