### ISSUE TITLE
fatal error: concurrent map iteration and map write dealing with short-living namespaces

### ISSUE THREAD

**Issue by elitvinov** [mittwald/kubernetes-replicator#216]
**Describe the bug**

Hi, we have the following config to replicate a docker private registry key across ~500 namespaces.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: docker-cred-secret
  annotations:
    replicator.v1.mittwald.de/replicate-to: "*"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${docker_config_json}
```

Namespaces are dynamically created and removed on regular basis. 
A pod running kubernetes-replicator is restarting hourly or more often due to
```
fatal error: concurrent map iteration and map write
```

**To Reproduce**
Create the above spec
Start 250 static namespaces
Start creating followed by termination 250 more namespaces constantly. Some namespaces live 10 seconds or less, some - not more than 1h. Aim is having a process of minimum 5 simultaneously namespaces termination

**Expected behavior**
kubernetes-replicator works fine without restarts

**Environment:**
 - Kubernetes version: **1.20**
 - kubernetes-replicator version: **v2.7.3**

**Additional context**

logs of failed pod:
```
time="2022-09-15T12:43:02Z" level=info msg="Secret replicator/docker-cred-secret to be replicated to: [*]" kind=Secret source=replicator/docker-cred-secret
time="2022-09-15T12:43:02Z" level=info msg="Checking if auto-ns-40888236/docker-cred-secret exists? false" kind=Secret source=replicator/docker-cred-secret target=auto-ns-40888236/docker-cred-secret
time="2022-09-15T12:43:02Z" level=debug msg="Creating a new secret secret auto-ns-40888236/docker-cred-secret" kind=Secret source=replicator/docker-cred-secret target=auto-ns-40888236/docker-cred-secret
time="2022-09-15T12:43:02Z" level=info msg="Replicated replicator/docker-cred-secret to: auto-ns-40888236" source=replicator/docker-cred-secret
fatal error: concurrent map iteration and map write

goroutine 5280 [running]:
runtime.throw(0x17f2bd1, 0x26)
	/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/panic.go:1117 +0x72 fp=0xc0070db550 sp=0xc0070db520 pc=0x4361f2
runtime.mapiternext(0xc0070db8a0)
	/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/map.go:858 +0x54c fp=0xc0070db5d0 sp=0xc0070db550 pc=0x410aac
github.com/mittwald/kubernetes-replicator/replicate/common.(*GenericReplicator).NamespaceAdded(0xc00003d130, 0xc000676160)
	/home/runner/work/kubernetes-replicator/kubernetes-replicator/replicate/common/generic-replicator.go:153 +0x208 fp=0xc0070dbfb8 sp=0xc0070db5d0 pc=0x146a6e8
github.com/mittwald/kubernetes-replicator/replicate/common.(*GenericReplicator).NamespaceAdded-fm(0xc000676160)
	/home/runner/work/kubernetes-replicator/kubernetes-replicator/replicate/common/generic-replicator.go:151 +0x3d fp=0xc0070dbfd8 sp=0xc0070dbfb8 pc=0x14733fd
runtime.goexit()
	/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0070dbfe0 sp=0xc0070dbfd8 pc=0x46ba81
created by github.com/mittwald/kubernetes-replicator/replicate/common.(*NamespaceWatcher).create.func1.1
	/home/runner/work/kubernetes-replicator/kubernetes-replicator/replicate/common/namespaces.go:40 +0x70
```

and so on (see a comment)

**Comment by martin-helmich** [comment]
Thanks for the thorough report, and apologies for the late reaction. I'll investigate when I find the time. In the meantime, PRs are also welcome. 🙂

**Comment by mFranz82** [comment]
We are facing the same problem with the latest version

**Comment by gecekleatsap** [comment]
Same here... this is really a blocker for clusters with larger amounts of secrets to be replicated.

**Comment by stippi2** [comment]
Hi. We had a first look into the issue.

- There is a [global Namespace informer](https://github.com/mittwald/kubernetes-replicator/blob/master/replicate/common/namespaces.go#L18). The `generic_replicator` uses it to [register](https://github.com/mittwald/kubernetes-replicator/blob/master/replicate/common/generic-replicator.go#L81-L82) hook functions to be informed on namespace additions and updates.
- The `generic_replicator` also uses its [own informer](https://github.com/mittwald/kubernetes-replicator/blob/master/replicate/common/generic-replicator.go#L67) to be notified of changes to other resources.
- Our understanding is that the functions that the Informers call, are called in dedicated Go routines.
- The same map is [iterated](https://github.com/mittwald/kubernetes-replicator/blob/master/replicate/common/generic-replicator.go#L153) from the `NamespaceAdded` hook as well as [written](https://github.com/mittwald/kubernetes-replicator/blob/master/replicate/common/generic-replicator.go#L270) from the `ResourceAdded` hook called by the other Informer.

We are currently looking into how we can contribute a fix. @martin-helmich: Would you be happy about a PR with a simple fix (like adding a `sync.Mutex` or using `sync.Map` instead), or would you rather prefer an extensive test validating the fix?
