### ISSUE TITLE
Inclusion of Priority Class in Helm Chart

### ISSUE THREAD

**Issue by jacob-kuder** [mittwald/kubernetes-replicator#226]
**Is your feature request related to a problem? Please describe.**
Not particularly - but thank you!

**Describe the solution you'd like**
It would be very helpful to have the priorityClassName parameter/setting added to the Helm chart so that we can add a priority to our replicator solution. We enjoy having the ability to set resource limits and requests, but would also like to set a priority as well.

**Describe alternatives you've considered**
Alternatives - none at the moment. There is seemingly no way to set this parameter at this time/this version (2.7.3).

**Additional context**
N/A

Thank you for your help and time and being open to configuring this parameter!

**Comment by adrianhernandez-stratio** [comment]
I agree with you. If you've already configured `priorityClass` in other artifacts in your cluster, it's helpful configure it in this chart also. :smile: 

Thanks!
