### ISSUE TITLE
Settings for log level

### ISSUE THREAD

**Issue by dreh23** [mittwald/kubernetes-replicator#24]
We use the replicator in production at a customer. We are getting complains over too many logs from the replicator. To the defence we have lots of apps and namespaces.

Any plans of introducing log levels?

Would you accept a merge request, let's say with a simple log library like hashicorp's [logutils](
https://github.com/hashicorp/logutils)?

**Comment by Hermsi1337** [comment]
Hey @dreh23 ,

log-levels are definitely a good idea. 
For now, we're using [logrus](https://github.com/sirupsen/logrus) in all of our projects.  

We greatly appreciate pull-requests, if you are willing to provide one. (:

Regards,

Hermsi
