### ISSUE TITLE
Does not work on arm machines

### ISSUE THREAD

**Issue by ciffelia** [mittwald/kubernetes-replicator#245]
**Describe the bug**

When I deploy this app on my arm cluster, the pod fails to start. The log says:

```
exec /replicator: exec format error
```

**To Reproduce**

On an arm cluster:

```sh
helm repo add mittwald https://helm.mittwald.de
helm repo update

helm upgrade --install kubernetes-replicator mittwald/kubernetes-replicator \
  --namespace kubernetes-replicator --create-namespace \
  --version 2.7.3

kubectl logs -n kubernetes-replicator kubernetes-replicator-xxxxxxxxxxxx-xxxxx
```

**Expected behavior**

The pod starts successfully.

**Environment:**
 - Kubernetes version: 1.24.8
 - kubernetes-replicator version: v2.7.3

**Additional context**

The problem is that `quay.io/mittwald/kubernetes-replicator:latest` is not a multi-arch image. I will create a PR to fix `.goreleaser.yml` to address this issue in a few days.

**Comment by oberlon** [comment]
Something new to this topic? Got the same problem on arm64.
