### ISSUE TITLE
New Release Timeline?

### ISSUE THREAD

**Issue by madrobs** [mittwald/kubernetes-replicator#264]
**Describe the bug**

Hey, looking to pick up the fix from https://github.com/mittwald/kubernetes-replicator/issues/215, is there a timeline for when it'll be released?

Would love to see this, seems odd there hasn't been a release in a few years?

**Comment by martin-helmich** [comment]
Hey! :wave:  Sorry for the late response -- I've just tagged a [v2.8.0 release](https://github.com/mittwald/kubernetes-replicator/releases/tag/v2.8.0).
