### ISSUE TITLE
how often does the controller check secrets for changes and re-synch?

### ISSUE THREAD

**Issue by gsfd2000** [mittwald/kubernetes-replicator#270]
if I do have a tls secret in namespace a with a label to synch to namespace b, how often or on what base is the controller checking the secret for changes in namespace a and re-synching them to the target namespace b (push mechanism applied)? Could not find any details on that matter. thx

also wanted to label this as question, pls advise how to do so. thx

**Comment by martin-helmich** [comment]
The replicator uses a WATCH request to stream changes in near-realtime. Additionally, the controller has a resync period of 30m (by default, configurable by flag) after which all observed secrets are synchronised, regardless of any previous changes.

Hope that helps!
