### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by desaintmartin** [mittwald/kubernetes-replicator#3]
Would you be open to have an helm chart to manage kubernetes-replicator? Manually managing helm objects make me nervous on production clusters. :)

**Comment by martin-helmich** [comment]
Sure! Pull requests are most welcome!

Am 25.01.2019 16:23 schrieb Cédric de Saint Martin <notifications@github.com>:

Would you be open to have an helm chart to manage kubernetes-replicator? Manually managing helm objects make me nervous on production clusters. :)

**Comment by martin-helmich** [comment]
Fixed in #4
