### ISSUE TITLE
Question Regarding Kubernetes-Replicator's Version Support Policy

### ISSUE THREAD

**Issue by mooneeb** [mittwald/kubernetes-replicator#302]
Hello 👋 👋 

Could someone please kindly let me know what is the version support policy and/or the kubernetes compatibility policy for kubernetes-replicator? :) Going through the documentation, I was not able to find this information and such information is really useful and helpful when we're planning our upgrades.

From the releases it looks like kubernetes-replicator supports the latest major.minor release (by support i mean release security patches and bug fixes etc). But I could be wrong and hence I would be grateful for the maintainer's response, guidance, and recommendation. 

Thank you 🙂

**Comment by martin-helmich** [comment]
Hey! :wave:   Currently, there is no explicitly defined compatibility policy for this project. De facto, the `k8s.io/client-go` dependency (which would be the main influential factor for Kubernetes version compatibility) is kept up-to-date automatically, so we implicitly support whichever k8s versions are supported by the latest client-go release (although the official compatibility matrix[^1] appears slightly out-of-date itself).

In practice, this operator only operates on `v1` APIs (`corev1` and `rbacv1`), which are more or less guaranteed to remain stable,[^2] so it should still be compatible to a relatively wide range of older releases.

Hope that helps, at least a bit. 🙂 

[^1]: https://github.com/kubernetes/client-go#compatibility-matrix
[^2]: https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-changes
