### ISSUE TITLE
Replication fails when destination is created before source

### ISSUE THREAD

**Issue by Bowbaq** [mittwald/kubernetes-replicator#33]
### Problem
When the destination secret is created before the source, `kubernetes-replicator` forgets about it. 

The real world use case for this is the following: we use `cert-manager` to issue a wildcard certificate, which gets store in a secret in the `kube-system` namespace. We then need to replicate this secret to several other namespaces. When configuring a new cluster, our tooling provisions `cert-manager` first, then `kubernetes-replicator` & then creates the empty secrets to accept the replicated data. This leads to a race condition where sometimes certificate issuance (and the corresponding creation of the source secret) happens after the creation of the destination secrets.

I believe the issue is this [branch](https://github.com/mittwald/kubernetes-replicator/blob/master/replicate/secrets.go#L93-L96) which exits early. This could be fixed by either:
- updating the dependency map even if the source secret does not exist. I'm not sure if this has other undesirable implications
- periodically reconciling state with the cluster by listing all secrets, or perhaps check for existing dependents when a source secret is created

### Reproduction
```bash
# Create destination secret & annotate it for replication
kubectl create secret generic test-destination
kubectl annotate secret test-destination replicator.v1.mittwald.de/replicate-from=default/test-source

# Create source secret & annotate it for replication
kubectl create secret generic test-source
kubectl annotate secret test-source replicator.v1.mittwald.de/replication-allowed=true
kubectl annotate secret test-source replicator.v1.mittwald.de/replication-allowed-namespaces='.*'
```

#### Expected
The `test-source` secret is replicated into the `test-destination` secret

#### Actual
Nothing happens.

```
-> % kubectl -n kube-system logs replicator-deployment-766c46874f-54bs2 --tail=10   
2020/02/14 23:05:05 secret default/better-tls-3.dev.source.ai-tls is already up-to-date
2020/02/14 23:05:05 secret jenkins/better-tls-3.dev.source.ai-tls is replicated from kube-system/better-tls-3.dev.source.ai-tls
2020/02/14 23:05:05 secret jenkins/better-tls-3.dev.source.ai-tls is already up-to-date
2020/02/14 23:05:05 secret kube-system/better-tls-3.dev.source.ai-tls has 2 dependents
2020/02/14 23:05:05 updating dependent secret kube-system/better-tls-3.dev.source.ai-tls -> default/better-tls-3.dev.source.ai-tls
2020/02/14 23:05:05 secret default/better-tls-3.dev.source.ai-tls is already up-to-date
2020/02/14 23:05:05 updating dependent secret kube-system/better-tls-3.dev.source.ai-tls -> jenkins/better-tls-3.dev.source.ai-tls
2020/02/14 23:05:05 secret jenkins/better-tls-3.dev.source.ai-tls is already up-to-date
2020/02/14 23:10:20 secret default/test-destination is replicated from default/test-source
2020/02/14 23:10:20 could not get secret default/test-source: does not exist
```

I'd be happy to take a crack at this but I wanted to touch base & see which way you'd rather go about fixing this

**Comment by martin-helmich** [comment]
Fixed in #34
