### ISSUE TITLE
Target tls secret not updated after a kubectl apply deleting the certificate

### ISSUE THREAD

**Issue by HansK-p** [mittwald/kubernetes-replicator#40]
Hello

I'm not sure if this is to be counted as a bug or a feature. I've validated this with Kubectl v.1.18.1 and AKS cluster v. 1.15.10. I've also validated that a K8s v.1.18.1 cluster behaves the same way.

Create a target tls secret:
<pre>
apiVersion: v1
kind: Secret
metadata:
  name: test-example-com-tls
  annotations:
    replicator.v1.mittwald.de/replicate-from: default/test-example-com-tls
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""
</pre>

Apply the target TLS secret.
Wait for the secret to be replicated.
Apply the target TLS secret again.

The second kubectl apply have emptied the value of tls.key and tls.crt, but without resetting the annotation `replicator.v1.mittwald.de/replicated-from-version.` As a result the, now empty, target secret is not updated again until the source secrete is updated.

Our current workaround is to apply a yaml file while which explicitly overwrites the annotation, that is:
<pre>
apiVersion: v1
kind: Secret
metadata:
  name: test-example-com-tls
  annotations:
    replicator.v1.mittwald.de/replicate-from: default/test-example-com-tls
    replicator.v1.mittwald.de/replicated-from-version: "0"
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""
</pre>
With this change the secret is replicated once again if we emty it by applying the yaml file one more  time

I assume the easiest way to solve this issue is to update the documentation (?).

Br

Hans K.

**Comment by martin-helmich** [comment]
Thanks for the report! Unfortunately, this is kind of to be expected; when specified with `tls.key: ""`, each `kubectl apply` will _always_  purge the secret data.

I don't have a really good solution for this off the top of my hat; resetting the `replicated-from-version` annotation certainly works, however you're going to have a (however brief) period of time where your secret will be invalid until the replicator kicks in again.

I'll give this some thought to see if we can come up with a better solution (@hensur, any ideas, maybe?). If not, we'll at least adjust the documentation accordingly.

**Comment by HansK-p** [comment]
Thanks for the followup

I assume a possible solution is to extend the design so that CRDs are used instead of (or in addition to) annotations.

It would also also be nice to use CRDs for secret sources. Especially when software like cert-manager is used to keep those source tls secrets up to date. I don't think cert-manager supports setting custom annotations on tls secrets it creates out of the box, but I don't think cert-manager deletes those annotations once they are there either. And I assume this is only relevant when cert-manager retrieves wildcard certificates and those source tls secret annotations are needed due to security.

I assume making such changes requires some work, might not be worth it and might not even be wise. So I fully understand it if you don't jump on such a (possible) solution to the problem.

Br

Hans K.

**Comment by martin-helmich** [comment]
@HansK-p The more I think about it, the more I like the CRD-based solution you are proposing, as it would solve quite a few of the issues that have been reported so far. I've put some more thought into this in #41 and would appreciate your thoughts.

Since this issue originally started as a bug report and has somewhat grown beyond that, I'd prefer closing this issue in favor of #41, if that is OK for you?
