### ISSUE TITLE
Namespace regexes match substrings

### ISSUE THREAD

**Issue by martin-helmich** [mittwald/kubernetes-replicator#48]
**Describe the bug**
When a secret is configured with a regex for matching allowed replication targets (for example, using an annotation like `replicator.v1.mittwald.de/replication-allowed-namespaces: "namespace-[0-9]*"`), the regex will also match substrings of the namespace name. This means that `foonamespace-123bar` will also be matched by `namespace-[0-9]*`.

**To Reproduce**
1. Create a secret with `replicator.v1.mittwald.de/replication-allowed-namespaces: "bar"`
2. Create a namespace `foobarbaz`
3. Create a secret within that namespace and replicate from the original secret
4. Profit!

**Expected behavior**
Secret should not be replicated. Or should it!? 🤔 

**Environment:**
 - Kubernetes version: irrelevant
 - kubernetes-replicator version: v2.3.0

**Additional context**
Credits to @bokysan for discovering this issue in #47

**Comment by bokysan** [comment]
IMO the proper way should follow the element of least surprise.

Eg. if annotation is `replicator.v1.mittwald.de/replication-allowed-namespaces: "foo,bar,baz"` I wouldn't expect it to match namespaces `tenderfoot`, `tenderfoot` or `bazar`.

**Comment by martin-helmich** [comment]
After some consideration, I completely agree. It probably does not make sense to work on this while #47 is still pending, but it should be an easy fix otherwise.

**Comment by t0st** [comment]
Hi Guys!

I just stumbled over this operator and love it!
Installed v2.4.0 just a few minutes ago and tested it but the issue mentioned here and in #42 is still present:

```
$ oc annotate secret letsencrypt-cert -n openshift-ingress replicator.v1.mittwald.de/replicate-to=openshift-config
secret/letsencrypt-cert annotated

time="2020-09-21T14:58:40Z" level=info msg="Secret openshift-ingress/letsencrypt-cert to be replicated to: [openshift-config]" kind=Secret source=openshift-ingress/letsencrypt-cert
time="2020-09-21T14:58:40Z" level=info msg="Checking if openshift-config/letsencrypt-cert exists? false" kind=Secret source=openshift-ingress/letsencrypt-cert target=openshift-config/letsencrypt-cert
time="2020-09-21T14:58:40Z" level=info msg="Checking if openshift-config-managed/letsencrypt-cert exists? false" kind=Secret source=openshift-ingress/letsencrypt-cert target=openshift-config-managed/letsencrypt-cert
time="2020-09-21T14:58:40Z" level=info msg="Checking if openshift-config-operator/letsencrypt-cert exists? false" kind=Secret source=openshift-ingress/letsencrypt-cert target=openshift-config-operator/letsencrypt-cert
```

You see - the secret should only get replicated in **openshift-config** and not in the other namespaces.

Do you need help here?
I could have a look at this issue and create a PR.

Regards
tost

**Comment by martin-helmich** [comment]
Hey @t0st! :wave: Thanks for your feedback.

>Do you need help here?
I could have a look at this issue and create a PR.

Sure. PRs are always welcome :)

**Comment by vsimon** [comment]
> You see - the secret should only get replicated in **openshift-config** and not in the other namespaces.

@t0st I think `replicator.v1.mittwald.de/replicate-to: "^openshift-config$"` would replicate only to the `openshift-config` namespace  and not in the other (`openshift-config-managed`, `openshift-config-operator`) namespaces. 

The project internally uses the standard regexp.MatchString function which reports if there any match of the regex string but it can also support stricter matching depending on the regex string given.
