### ISSUE TITLE
Support for pushing secrets instead of pulling

### ISSUE THREAD

**Issue by sheerun** [mittwald/kubernetes-replicator#5]
Would it be possible to configure resources in privileged namespace to push secrets to less privileged namespace instead of other way around? I think ability to pull secrets from any namespace isn't very secure

**Comment by sheerun** [comment]
It would be another solution to #2 i.e. disallow pulling secrets, and allow only pushing them

**Comment by MoShitrit** [comment]
Looks like this was solved via #47 
Looking forward to get this release 😄
