### ISSUE TITLE
Question regarding how to build the Docker image properly

### ISSUE THREAD

**Issue by MoShitrit** [mittwald/kubernetes-replicator#52]
Hey there!
First of all- thanks so much for building this great tool! It's really useful for us here 😄 

I've been struggling with an issue since yesterday and figured it might be worth asking here.
When I build the binary locally from `master` (using `go build`) and run it pointing to a local `kubeconfig` file- it works well. 
However, if I build the image using the main `Dockerfile` (not the `.buildx` one) and then deploy it to the same cluster- it doesn't seem to function the same way (for example, the "push-based" replication doesn't seem to work. I see in the logs when using `--log-level debug` that the secrets are pushed to desired namespaces, but then nothing gets really created).
I'm pretty sure I'm doing something wrong with how I'm building the Docker image, and since it seems like a process I haven't interacted with before (I noticed that `buildx` is a newly added experimental feature) - I'm not really sure how can I mimic the same process that is done when a release is made.
I'd love to get some pointing in the right direction on how to accomplish this task. The push-based replication is something we _really_ look forward to.

**Comment by martin-helmich** [comment]
>I'm not really sure how can I mimic the same process that is done when a release is made.

The actual release images are built using [GoReleaser](https://goreleaser.com/). With GoReleaser installed, you should be able to build a nightly image using `goreleaser release --snapshot --skip-publish`. Hope that helps!

**Comment by MoShitrit** [comment]
That worked perfectly, thanks @martin-helmich !
So about a new release- is there any ETA / plan to officially introduce this new feature with a release?
FWIW- I just deployed that image in my test cluster and verified that it works as expected. (I also create #53 with a quick fix I found)

**Comment by martin-helmich** [comment]
Happy to help -- and also thanks for your efforts in testing this. I think there's nothing thats holding up a new release, except maybe #48; but we can always add the fix for that one in a subsequent release...

**Comment by martin-helmich** [comment]
@MoShitrit Just tagged [v2.4.0](https://github.com/mittwald/kubernetes-replicator/releases/tag/v2.4.0) -- release should be available shortly.

**Comment by MoShitrit** [comment]
Perfect, thanks so much @martin-helmich !! 😄😄
