### ISSUE TITLE
Behavior when secret with the same name already exists

### ISSUE THREAD

**Issue by OuesFa** [mittwald/kubernetes-replicator#56]
Hello 👋 
What does the controller do when there is already an existing secret with the same name (but not necessarily the same data) in the target namespace please ?
Thank you !

**Comment by martin-helmich** [comment]
When encountering an already-existing secret, the contents of both secrets will be merged, with the values from the source secret taking precedence. When the source secret is deleted at some point, all data items replicated from that secret will be removed, while values that were originally present in the target secret will remain.

https://github.com/mittwald/kubernetes-replicator/blob/4049487b6975bcdfd3da52255e5aefd1e15ed81a/replicate/secret/secrets.go#L81-L98
