### ISSUE TITLE
Copy ConfigMap labels if they exist in source

### ISSUE THREAD

**Issue by cromark** [mittwald/kubernetes-replicator#57]
**Is your feature request related to a problem? Please describe.**
Created/Updated configmap does not contain labels from original configmap.

**Describe the solution you'd lgmapike**
Labels copied , if they exist in the source configmap

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by kolorful** [comment]
hmm it seems like https://github.com/kolorful/kubernetes-replicator/blob/master/replicate/configmaps.go#L124 should do the work, but the labels are not copied over somehow.
