### ISSUE TITLE
Delete replicated resources when source is deleted

### ISSUE THREAD

**Issue by c4tz** [mittwald/kubernetes-replicator#65]
Hey there,

first of all: thank you for this awesome piece of software. :) I am planning on replacing `kubed` with `kubernetes-replicator`, as it seems more stable, better maintained and supports more resource types.

There is just one thing I am missing currently from `kubernetes-replicator`: When deleting the source resource (for example a configmap, in my case), the replicated/dependant ones should be deleted as well `if` they only contain replicated fields. From reading other issues, I know you're already checking the fields, so I hope it might not be a big change/implementation.

Or is there maybe another reason (I cannot think of yet) why you didn't include that feature yet?

**Comment by martin-helmich** [comment]
Hey @c4tz! Thanks for your feedback and the suggestion.

I think there's no particular reason that this feature isn't included, apart from nobody thinking of it. In general, I think there are two cases that need to be considered:

- Manually created target secrets with a `.../replicate-from` annotation: These secrets are manually created by a user (and then populated by the controller). In my opinion, deleting those secrets would be quite a surprise (as in "principle of least surprise") for the user (and the replicated keys are removed anyway, as discussed in #42).
- Automatically created target secrets (from a source with a `.../replicate-to` annotation: These secrets are created automatically by the controller. In this case, as a user, I would presumably not be surprised if these were also deleted automatically.

Any thoughts? Regarding any implementation work, I cannot make any promises as to when (or even if) we'd eventually get to building this -- as always, any PRs are more than welcome.

**Comment by c4tz** [comment]
Thank you for the response and suggestions, @martin-helmich.

Good to hear that there is no reason to not build this feature! Yes, I think the pulling target resources should not be deleted, too. Unfortunately I'm not confident/experienced enough in Golang (yet) to create a PR for this and do not have time to dive further into it currently, so I'll have to pass and wait.

**Comment by veophi** [comment]
This idea sounds very good!  I want to know whether this deletion logic is implemented?
