### ISSUE TITLE
"Secret does not exist" fake news

### ISSUE THREAD

**Issue by lucascollino** [mittwald/kubernetes-replicator#8]
Our dev cluster was aiming at the latest quay image, we had some certs issues and saw errors relating secrets in the replicator logs:

```
2019/03/18 19:13:42 secret kube-system/sandbox-dev-some-company-tls is replicated from cert-manager/sandbox-wdev-fintechpeople-ninja-tls
2019/03/18 19:13:42 could not get secret cert-manager/sandbox-wdev-fintechpeople-ninja-tls: does not exist
2019/03/18 19:13:42 secret jenkins/sandbox-wdev-fintechpeople-ninja-tls is replicated from cert-manager/sandbox-wdev-fintechpeople-ninja-tls
2019/03/18 19:13:42 could not get secret cert-manager/sandbox-wdev-fintechpeople-ninja-tls: does not exist
2019/03/18 19:13:42 secret vault/sandbox-wdev-fintechpeople-ninja-tls is replicated from cert-manager/sandbox-wdev-fintechpeople-ninja-tls
2019/03/18 19:13:42 replication of secret cert-manager/sandbox-wdev-fintechpeople-ninja-tls is not permitted: source cert-manager/sandbox-wdev-fintechpeople-ninja-tls does not allow replication. sandbox-wdev-fintechpeople-ninja-tls will not be replicated
```

cert-manager/sandbox-wdev-fintechpeople-ninja-tls exists and has valid cert
kube-system and jenkins secrets exist and have the correct content, so no update should be needed
The error not allowing replication is new, which I believe is fine according to the changes I saw in the code.

1- Is the behaviour about secret not existing expected?
2-  This kind of affected our use-case, as we create the secret with cert-manager and we depend on cert-manager never removing whatever annotations we manually add to that secret. Do you have a way in mind to mimic previous behavior not needing origin secret to have replicator annotations?

**Comment by martin-helmich** [comment]
>Is the behaviour about secret not existing expected?

Nope, this should not happen. Are the two secrets (source and target) created simultaneously? The replicator is working on a local cache; maybe it took a while to catch up.

>Do you have a way in mind to mimic previous behavior not needing origin secret to have replicator annotations?

Yes, it's even already implemented, although not broadly advertised. You can start the replicator with the `-allow-all` flag to restore the previous behaviour -- that we consider to be not totally secure (at least in a cluster with potentially untrustworthy actors).

Regarding the breaking change in behaviour; up until recently, this controller was still in an alpha release. At the same time, it was desirable for us to change this controller's behaviour to a more secure default -- meaning to explicitly whitelist which secrets could be replicated to which target (reasoning by a contributor in #2). We felt that the best time to introduce such a breaking change was while still in alpha; however, we could have communicated the breaking change more clearly -- sorry if it broke your setup.

Btw, we have stable release out by now, so we'll do our very best to avoid any future breaking changes from now on.

Let me know if this helped you with your question.

**Comment by lucascollino** [comment]
Adding the annotation:

```
2019/03/18 19:35:29 secret monitoring/sandbox-dev-some-company-tls is replicated from cert-manager/sandbox-dev-some-company-tls
2019/03/18 19:35:29 could not get secret cert-manager/sandbox-dev-some-company-tls: does not exist
2019/03/18 19:35:29 secret kube-system/sandbox-dev-some-company-tls is replicated from cert-manager/sandbox-dev-some-company-tls
2019/03/18 19:35:29 could not get secret cert-manager/sandbox-dev-some-company-tls: does not exist
2019/03/18 19:35:29 secret vault/sandbox-dev-some-company-tls is replicated from cert-manager/sandbox-dev-some-company-tls
2019/03/18 19:35:29 secret vault/sandbox-dev-some-company-tls is already up-to-date
2019/03/18 19:35:29 secret jenkins/sandbox-dev-some-company-tls is replicated from cert-manager/sandbox-dev-some-company-tls
2019/03/18 19:35:29 updating secret jenkins/sandbox-dev-some-company-tls
2019/03/18 19:35:29 secret jenkins/sandbox-dev-some-company-tls is replicated from cert-manager/sandbox-dev-some-company-tls
2019/03/18 19:35:29 secret jenkins/sandbox-dev-some-company-tls is already up-to-date                                                                                                                                                         
```

**Comment by lucascollino** [comment]
Awesome, thank you for the quick reply!

I'm aware about it being in alpha before, that's the reason of the "kind of".

I was just pointed out that cert-manager only updates the secret so no issues with annotations.

Thanks again!

**Comment by lucascollino** [comment]
For anyone finding an issue with this, here's a working example with the previous behavior:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: replicator-deployment
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: replicator
    spec:
      serviceAccountName: replicator
      containers:
        - name: replicator
          image: quay.io/mittwald/kubernetes-replicator:v1.0.0
          command: ["/replicator"]
          args: ["--allow-all"]   
```

**Comment by aehaynes** [comment]
I'm still getting this issue even with the "--allow-all" args as lucascollino showed above:

`2019/06/20 13:29:58 using in-cluster configuration
2019/06/20 13:29:58 running config map controller
2019/06/20 13:29:58 running secret controller
2019/06/20 13:29:58 secret development-tkdb/tkdb-secret is replicated from kube-certificates/dev-tkdb-com-tls-2
2019/06/20 13:29:58 could not get secret kube-certificates/dev-tkdb-com-tls-2: does not exist`

**Comment by aehaynes** [comment]
Specifiying  `args: ["--resync-period=1m" ]` in the deployment fixed my issue
