### ISSUE TITLE
quay.io/mittwald/kubernetes-replicator

### ISSUE THREAD

**Issue by stroncium** [mittwald/kubernetes-replicator#9]
Helm chart defaults to:

image: `quay.io/mittwald/kubernetes-replicator`
tag: `stable`

https://quay.io/repository/mittwald/kubernetes-replicator?tab=tags shows that stable tag is assigned to year old alpha build image(considering it shares `v1.0.0-alpha1` tag).

As a result, helm chart deployments never go healthy/ready(after some initial logs with no errors) and go to CrashLoopBackOff later.

Can be fixed by changing default image tag to `latest` / `v1.0.0`, but I believe the real error is tag assigned to incorrect image.

**Comment by martin-helmich** [comment]
You're right, `stable` should point to `1.0.0`. Fixed.
